// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFiles(arg1:Array<string>):Promise<Array<main.FileItem>>;

export function AddServicePatternHistory(arg1:string):Promise<void>;

export function AnalyzeFiles():Promise<void>;

export function ClearCache():Promise<void>;

export function ClearFiles():Promise<void>;

export function DeleteAPIKey(arg1:string):Promise<void>;

export function DeselectAll():Promise<void>;

export function GetAPIKey(arg1:string):Promise<string>;

export function GetAvailableModels():Promise<Array<string>>;

export function GetCacheCount():Promise<number>;

export function GetConfig():Promise<main.ConfigInfo>;

export function GetFiles():Promise<Array<main.FileItem>>;

export function GetServicePatternHistory():Promise<Array<string>>;

export function GetSettings():Promise<main.SettingsInfo>;

export function HasAPIKey():Promise<boolean>;

export function OnFileOpen(arg1:string):Promise<void>;

export function OpenFileDialog():Promise<Array<string>>;

export function OpenFolderDialog():Promise<string>;

export function RenameFiles():Promise<main.RenameResult>;

export function SaveAPIKey(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSettingsWithModel(arg1:string,arg2:string):Promise<void>;

export function ScanFolder(arg1:string):Promise<Array<string>>;

export function SelectAll():Promise<void>;

export function ToggleFileSelection(arg1:number):Promise<void>;

export function UpdateServicePattern(arg1:string):Promise<void>;
