// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFiles(arg1) {
  return window['go']['main']['App']['AddFiles'](arg1);
}

export function AnalyzeFiles() {
  return window['go']['main']['App']['AnalyzeFiles']();
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function ClearFiles() {
  return window['go']['main']['App']['ClearFiles']();
}

export function DeleteAPIKey(arg1) {
  return window['go']['main']['App']['DeleteAPIKey'](arg1);
}

export function DeselectAll() {
  return window['go']['main']['App']['DeselectAll']();
}

export function GetAPIKey(arg1) {
  return window['go']['main']['App']['GetAPIKey'](arg1);
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetCacheCount() {
  return window['go']['main']['App']['GetCacheCount']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HasAPIKey() {
  return window['go']['main']['App']['HasAPIKey']();
}

export function OnFileOpen(arg1) {
  return window['go']['main']['App']['OnFileOpen'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function RenameFiles() {
  return window['go']['main']['App']['RenameFiles']();
}

export function SaveAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SaveAPIKey'](arg1, arg2);
}

export function SaveSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3);
}

export function SaveSettingsWithModel(arg1, arg2) {
  return window['go']['main']['App']['SaveSettingsWithModel'](arg1, arg2);
}

export function ScanFolder(arg1) {
  return window['go']['main']['App']['ScanFolder'](arg1);
}

export function SelectAll() {
  return window['go']['main']['App']['SelectAll']();
}

export function ToggleFileSelection(arg1) {
  return window['go']['main']['App']['ToggleFileSelection'](arg1);
}

export function UpdateServicePattern(arg1) {
  return window['go']['main']['App']['UpdateServicePattern'](arg1);
}
